{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.expose.tls.cert.secretName }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- if .Values.persistenceKeep }}
    "helm.sh/resource-policy": keep
    {{- end }}
  name: {{ .Values.expose.tls.cert.secretName }}
  labels:
{{ include "fogedge.labels" . | indent 4 }}
type: kubernetes.io/tls
{{- if eq .Values.expose.tls.cert.certSource "auto" }}
{{- if $secret }}
data: 
{{ toYaml $secret.data | indent 2 }}
{{- else }}
data:
  {{- $ca := genCA "fogedge-ca" 36500 }}
  {{- $cert := genSignedCert "fogedge" .Values.expose.tls.cert.ipTables .Values.expose.tls.cert.dnsNames 3650 $ca }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
{{- end }}
{{- else if eq .Values.expose.tls.cert.certSource "manual" }}
data:
  ca.crt: {{ .Values.expose.tls.cert.ca | b64enc | quote }}
  tls.key: {{ .Values.expose.tls.cert.key | b64enc | quote }}
  tls.crt: {{ .Values.expose.tls.cert.crt | b64enc | quote }}
{{- end }}