{{ if eq .Values.expose.type "Ingress" }}
{{ if .Values.expose.Ingress.createClass }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.expose.Ingress.className }}
  annotations: 
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  controller: {{ .Values.expose.Ingress.controller }}
{{ end }}
{{ end }}